### ISSUE TITLE
Function error.

### ISSUE THREAD

**Issue by subratkatiyar** [subratkatiyar/Encryption_Library#3]
@gaganyadav80 
![image](https://user-images.githubusercontent.com/43543908/94996534-dfb66900-05c2-11eb-8e6d-537e9713cac7.png)
Should be an easy fix.

Also add an feature to join the room, if new room was created.
![image](https://user-images.githubusercontent.com/43543908/94996643-8569d800-05c3-11eb-90a1-1e0249c45f73.png)

**Comment by gaganyadav80** [comment]
1. The function error is due to the edited library for assigning the displayName when new account is created (Signup)
    - Open the pyrebase package
    - Edit the `create_user_with_email_and_password()` from this:
           `def create_user_with_email_and_password(self, email, password):`
       To this:
           `def create_user_with_email_and_password(self, email, password, name):`

    OR
        - Simply don't pass the name argument in create_user() function in the firebase/firebase.py

2. If a user creats a chatroom it means he joined the chatroom automatically, no need to mention. As there is no GUI and chats feature is not included yet hence no futher thing is added when chat room is created
