### ISSUE TITLE
Unable to join chat room.

### ISSUE THREAD

**Issue by subratkatiyar** [subratkatiyar/Encryption_Library#4]
@gaganyadav80 
![image](https://user-images.githubusercontent.com/43543908/94996695-c82bb000-05c3-11eb-856c-eb14f91b8678.png)

**Comment by gaganyadav80** [comment]
That is beacuse of the function error in Singup and hence function was not able to catcht he "userID" and as it was used to identify the chat_rooms created by that user, the chat_room was not created in the first place technically and hence you cannot join. It's just the python code showing chatroom create while the data was not pushed to firebase (catch exception will be added)

Will be fixed in next commit. :)
